apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-prod
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Amertz08/gitops-infra
        revision: HEAD
        directories:
          - path: apps/*/*/overlays/prod
  template:
    metadata:
      name: '{{path[1]}}-{{path[2]}}-{{path[4]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Amertz08/gitops-infra
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: prod-cluster
        namespace: '{{path[1]}}-{{path[4]}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
