apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'envoy-gateway-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Amertz08/gitops-infra
        targetRevision: HEAD
        path: infrastructure/envoy-gateway
      destination:
        name: '{{name}}'
        namespace: envoy-gateway-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
